name: Build en Deploy Compiiile site
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setup perms!!
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-en-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5

      - name: Install en build
        run: |
          npm ci
          npm run build

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .compiiile/dist
          branch: gh-pages
